apiVersion: v1
kind: Service
metadata:
  name: orderservice
spec:
  selector:
    app: orderservice
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderservice
  labels:
    app: orderservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderservice
  template:
    metadata:
      labels:
        app: orderservice
    spec:
      terminationGracePeriodSeconds: 30
      hostname: orderservice
      subdomain: orderservice
      containers:
        - name: orderservice
          image: docker.raqeebwedsrabeeta.live:5000/rabeeta/order_service:build-number
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8080
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP